---ISO 639-1 code	  ---
--[[
['aao'] = { name='عربية صحراوية جزائرية',codes={	'aao'}},
['abh'] = { name='عربية طاجكية',codes={	'abh'}},
['abv'] = { name='عربية بحرانية',codes={	'abv'}},
['acm'] = { name='عربية عراقية',codes={	'acm'}},
['acq'] = { name='عربية تعزية عدنية',codes={	'acq'}},
['acw'] = { name='عربية حجازية',codes={	'acw'}},
['acx'] = { name='عربية عمانية',codes={	'acx'}},
['acy'] = { name='عربية قبرصية',codes={	'acy'}},
['adf'] = { name='عربية ظفارية',codes={	'adf'}},
['aeb'] = { name='عربية تونسية',codes={	'aeb'}},
['aec'] = { name='عربية صعيدية',codes={	'aec'}},
['afb'] = { name='عربية خليجية',codes={	'afb'}},
['ajp'] = { name='عربية شامية',codes={	'ajp'}},
['apc'] = { name='عربية شامية',codes={	'apc'}},
['apd'] = { name='عربية سودانية',codes={	'apd'}},
['arb'] = { name='عربية حديثة',codes={	'arb'}},
['arq'] = { name='عربية جزائرية',codes={	'arq'}},
['ars'] = { name='عربية نجدية',codes={	'ars'}},
['ary'] = { name='عربية مغربية',codes={	'ary'}},
['arz'] = { name='عربية مصرية',codes={	'arz'}},
['ayh'] = { name='عربية حضرمية',codes={	'ayh'}},
['ayl'] = { name='عربية ليبية',codes={	'ayl'}},
['ayn'] = { name='عربية صنعاوية',codes={	'ayn'}},
['auz'] = { name='عربية أزبكية',codes={	'auz'}},
['avl'] = { name='عربية بداوية مصرية شرقية',codes={	'avl'}},
['ayp'] = { name='عربية عراقية شمالية',codes={	'ayp'}},
['bbz'] = { name='عربية كريولية ببلية',codes={	'bbz'}},
--['de-at'] = { name='ألمانية نمساوية',codes={'de-at'}},
--['de_AT']={ name='ألمانية نمساوية',codes={'de_AT'}},
--['en-ca'] = { name='إنجليزية كندية',codes={'en-ca','en_ca','en_CA'}},
--['en-gb'] = { name='إنجليزية بريطانية',codes={'en-gb','en_GB','en_gb'}},
--['en_AU']={ name='إنجليزية أسترالية',codes={'en_AU','en-au','en_au'}},
--['en_US']={ name='إنجليزية أمريكية',codes={'en_US','en-us','en_us'}},
]]
local data = {}
data.lang_table = {
    und = { name = "غير معروفة", al_name = "غير المعروفة", codes = {} },
    aa = { name = "عفارية", names = { "أفارية" }, codes = { "aar", "aars" } },
    tt = { name = "تتارية", names = { "تترية" }, codes = { "tat" } },

    ['anp'] = { name = 'أنجيكية', codes = {} },
    ab = { name = "أبخازية", codes = { "abk", "abks" } },
    ace = { name = "أتشينيزية", codes = {} },
    ach = { name = "أكولية", codes = {} },
    ada = { name = "أدانجمية", codes = {} },
    ady = { name = "أديغية", codes = {} },
    ae = { name = "أفستية", codes = { "ave" } },
    af = { name = "أفريقانية", codes = { "afr", "afrs" } },
    afh = { name = "أفريهيلية", codes = {} },
    ags = { name = "إسمبية", codes = {} },
    ain = { name = "آينوية", codes = {} },
    ak = { name = "أكانية", codes = { "aka" } },
    akk = { name = "أكادية", codes = {} },
    ale = { name = "أليوتية", codes = {} },
    als = { name = "توسك ألبانية", codes = {} },
    alt = { name = "ألطائية جنوبية", codes = {} },
    am = { name = "أمهرية", codes = { "amh" } },
    an = { name = "أراغونية", codes = { "arg" } },
    ang = { name = "إنجليزية قديمة", codes = {} },
    ar = { name = "عربية", codes = { "ara", "aao", "abh", "abv", "acm", "acq", "acw", "acx", "adf", "aeb", "aec", "afb", "ajp", "apc", "apd", "arb", "arq", "ars", "ary", "arz", "ayh", "ayl", "ayn", "auz", "avl", "ayp", "bbz", "acy" } },
    arc = { name = "آرامية", codes = {} },
    arn = { name = "مابوتشية", codes = {} },
    arw = { name = "أراواكية", codes = {} },
    ar_001 = { name = "عربية رسمية حديثة", codes = {} },
    as = { name = "آسامية", codes = { "asm" } },
    ast = { name = "أستورية", codes = {} },
    av = { name = "أوارية", codes = { "ava" } },
    awa = { name = "أوادية", codes = {} },
    ay = { name = "أيمارا", codes = { "aym" } },
    az = { name = "أذرية", codes = { "aze" } },
    azb = { name = "أذرية جنوبية", codes = {} },
    ba = { name = "باشقيرية", codes = { "bak" } },
    bal = { name = "بلوشية", codes = {} },
    ban = { name = "بالية", codes = {} },
    bar = { name = "بافارية", codes = {} },
    bbc = { name = "باتاك توبا", codes = {} },
    bcc = { name = "جنوبية بولشية", codes = {} },
    bcl = { name = "بيكولية وسطى", codes = {} },
    be = { name = "بيلاروسية", codes = { "bel" } },
    ["be-tarask"] = { name = "تاراتسكييفيتسا", codes = {} },
    ber = { name = "أمازيغية", codes = {} },
    bg = { name = "بلغارية", codes = { "bul", "buls" } },
    bgn = { name = "بلوشية غربية", codes = {} },
    bh = { name = "بهارية", codes = { "bih" } },
    bho = { name = "بوجبورية", codes = {} },
    bi = { name = "بسلاما", codes = { "bis" } },
    bik = { name = "بيكولية", codes = {} },
    bin = { name = "بينية", codes = {} },
    bjn = { name = "بنجرية", codes = {} },
    bla = { name = "سيكسيكية", codes = {} },
    bm = { name = "بمبرية", codes = { "bam" } },
    bn = { name = "بنغالية", codes = { "ben" } },
    bo = { name = "تبتية", codes = { "bod", "tib", "bod" } },
    br = { name = "بريتانية", codes = { "bre" } },
    bra = { name = "براجية", codes = {} },
    bs = { name = "بوسنوية", codes = { "bos", "boss" } },
    bua = { name = "برياتية", codes = {} },
    bug = { name = "بجينيزية", codes = {} },
    bxr = { name = "بوريات", codes = {} },
    byn = { name = "بلينية", codes = {} },
    ca = { name = "كتالونية", codes = { "cat" } },
    ["ca-valencia"] = { name = "بلنسية", codes = {} },
    car = { name = "كاريبية", codes = {} },
    cay = { name = "كايوجية", codes = {} },
    ce = { name = "شيشانية", codes = { "che" } },
    ceb = { name = "سيبونية", codes = {} },
    ch = { name = "تسمورية", codes = { "cha" } },
    chk = { name = "تشكيزية", codes = {} },
    cho = { name = "تشكطوية", codes = {} },
    chr = { name = "شيروكي", codes = {} },
    ckb = { name = "سورانية كردية", codes = {} },
    ckt = { name = "تشوكشي", codes = {} },
    cnr = { name = "مونتنغرية", codes = {} },
    co = { name = "كورسية", codes = { "cos", "قرشقية" } },
    cop = { name = "قبطية", codes = {} },
    cr = { name = "كرية", codes = { "cre" } },
    crh = { name = "تتارية قرمية", codes = {} },
    crs = { name = "كريولية سيشيلية", codes = {} },
    cs = { name = "تشيكية", codes = { "ces", "cze", "ces" } },
    csb = { name = "كاشوبية", codes = {} },
    cu = { name = "سلافونية كنسية قديمة", codes = { "chu" } },
    cv = { name = "تشوفاش", codes = { "chv" } },
    cy = { name = "ويلزية", codes = { "cym", "wel", "cym" } },
    da = { name = "دنماركية", codes = { "dan" } },
    dag = { name = "دغبانية", codes = {} },
    de = { name = "ألمانية", codes = { "deu", "ger", "deu", "deus", "de-at", "de_AT" } },
    ["de-ch"] = { name = "ألمانية عليا سويسرية", codes = {} },
    den = { name = "سلافية", codes = {} },
    din = { name = "دينكاوية", codes = {} },
    dje = { name = "زارمية", codes = {} },
    doi = { name = "دوجرية", codes = {} },
    dsb = { name = "صوربية سفلى", codes = {} },
    dv = { name = "ديفهي", codes = { "div" } },
    dz = { name = "دزونكا", codes = { "dzo" } },
    dzg = { name = "قرعانية", codes = {} },
    ee = { name = "إوية", codes = { "ewe" } },
    egl = { name = "إميليانو", codes = {} },
    egy = { name = "مصرية قديمة", codes = {} },
    el = { name = "يونانية", codes = { "ell", "gre", "ell", "ells" } },
    en = { name = "إنجليزية", codes = { "eng", "engs", "إنجليزي", "en-gb", "en_GB", "en-ca", "en_ca", "en_AU", "en-au", "en_au", "en_US", "en-us", "en_us" } },
    enm = { name = "إنجليزية وسطى", codes = {} },
    eo = { name = "إسبرانتو", codes = { "epo" } },
    es = { name = "إسبانية", codes = { "spa", "es_ES", "es-es" } },
    ["es-419"] = { name = "إسبانية أمريكية", codes = {} },
    es_MX = { name = "إسبانية مكسيكية", codes = {} },
    et = { name = "إستونية", codes = { "est" } },
    eu = { name = "بشكنشية", codes = { "eus", "baq", "eus" } },
    fa = { name = "فارسية", codes = { "fas", "per", "fas" } },
    fat = { name = "فانتية", codes = {} },
    ff = { name = "فولانية", codes = { "ful" } },
    fi = { name = "فنلندية", codes = { "fin" } },
    fil = { name = "فلبينية", codes = {} },
    fit = { name = "منكيلي", codes = {} },
    fj = { name = "فيجية", codes = { "fij" } },
    fo = { name = "فاروية", codes = { "fao" } },
    fr = { name = "فرنسية", codes = { "fra", "fre", "fra", "fras" } },
    frc = { name = "فرنسية كاجونية", codes = {} },
    fro = { name = "فرنسية قديمة", codes = {} },
    frr = { name = "فريزينية شمالية", codes = {} },
    frs = { name = "فريزينية شرقية", codes = {} },
    fr_CA = { name = "فرنسية كندية", codes = {} },
    fr_CH = { name = "فرنسية سويسرية", codes = {} },
    fy = { name = "فريزية غربية", codes = { "fry" } },
    ga = { name = "أيرلندية", codes = { "gle" } },
    gan = { name = "غان صينية", codes = {} },
    gd = { name = "غيلية إسكتلندية", codes = { "gla" } },
    gez = { name = "جعزية", codes = {} },
    gl = { name = "غاليسية", codes = { "glg" } },
    gn = { name = "غوارانية", codes = { "grn" } },
    gom = { name = "جواني كونكانية", codes = {} },
    got = { name = "قوطية", codes = {} },
    grc = { name = "إغريقية", codes = {} },
    gsw = { name = "ألمانية سويسرية", codes = {} },
    gu = { name = "كجراتية", codes = { "guj" } },
    guz = { name = "غيزية", codes = {} },
    gv = { name = "منكية", codes = { "glv" } },
    ha = { name = "هوسية", codes = { "hau" } },
    hak = { name = "هاكا صينية", codes = {} },
    haw = { name = "هاوائية", codes = {} },
    hbo = { name = "عبرية توراتية", codes = {} },
    he = { name = "عبرية", codes = { "heb" } },
    hi = { name = "هندية", codes = { "hin", "hins" } },
    hif = { name = "فيجي هندية", codes = {} },
    hit = { name = "حثية", codes = {} },
    hmn = { name = "همونجية", codes = {} },
    ho = { name = "هيري موتو", codes = { "hmo" } },
    hr = { name = "كرواتية", codes = { "hrv", "scr" } },
    ht = { name = "كريولية هايتية", codes = { "hat" } },
    hu = { name = "مجرية", codes = { "hun" } },
    hy = { name = "أرمنية", codes = { "hye", "arm", "hye" } },
    hz = { name = "هيريرو", codes = { "her" } },
    ia = { name = "إنترلنغوا", codes = { "ina" } },
    id = { name = "إندونيسية", codes = { "ind" } },
    ie = { name = "إنترلينج", codes = { "ile" } },
    ig = { name = "إيجبو", codes = { "ibo" } },
    ii = { name = "نؤوسوية", codes = { "iii" } },
    ik = { name = "إينبياك", codes = { "ipk" } },
    ike = { name = "آيكية", codes = {} },
    ilo = { name = "إيلوكانوية", codes = {} },
    inh = { name = "إنجوشية", codes = {} },
    io = { name = "إيدو", codes = { "ido", "idos" } },
    is = { name = "آيسلندية", codes = { "isl", "ice", "isl" } },
    it = { name = "إيطالية", codes = { "ita", "itas" } },
    iu = { name = "إنكتيتوتية", codes = { "iku" } },
    ja = { name = "يابانية", codes = { "jpn", "ja-Hani" } },
    jmc = { name = "ماتشامية", codes = {} },
    jpr = { name = "فارسية يهودية", codes = {} },
    jrb = { name = "عربية يهودية", codes = {} },
    jv = { name = "جاوية", codes = { "jav" } },
    ka = { name = "جورجية", codes = { "kat", "geo", "kat" } },
    kab = { name = "قبائلية (جزائرية)", codes = {} },
    kbd = { name = "قبردينية", codes = {} },
    kcg = { name = "تايابية", codes = {} },
    kg = { name = "كونغو", codes = { "kon" } },
    kha = { name = "كازية", codes = {} },
    khw = { name = "كهوار", codes = {} },
    ki = { name = "كيكيو", codes = { "kik" } },
    kj = { name = "كيونياما", codes = { "kua" } },
    kk = { name = "قازاقية", codes = { "kaz" } },
    kl = { name = "غرينلاندية", codes = { "kal" } },
    km = { name = "خميرية", codes = { "khm" } },
    kn = { name = "كنادية", codes = { "kan" } },
    ko = { name = "كورية", codes = { "ko", "kor", "kp-Hanj", "ko-Hang", "ko-hang", "ko-Hang-KP", "ko-Hang-KR", "ko-Hani", "ko-Hant", "ko-Hant-KP", "ko-Kana", "ko-Kang", "ko-Kore", "ko-KP", "ko-Latn", "ko-kp" } },
    kok = { name = "كونكانية", codes = {} },
    kr = { name = "كانورية", codes = { "kau" } },
    krl = { name = "كاريلية", codes = {} },
    ks = { name = "كشميرية", codes = { "kas" } },
    ["ks-Deva"] = { name = "كشميرية ديفنغارية", codes = {} },
    ksh = { name = "كولشية", codes = {} },
    ["ksh-x-colog"] = { name = "كولونيانية", codes = {} },
    ku = { name = "كردية", codes = { "kur" } },
    kum = { name = "قموقية", codes = {} },
    kv = { name = "كومية", codes = { "kom" } },
    kw = { name = "كورنية", codes = { "cor" } },
    ky = { name = "قيرغيزية", codes = { "kir" } },
    la = { name = "لاتينية", codes = { "lat", "lats" } },
    lb = { name = "لوكسمبورغية", codes = { "ltz" } },
    lez = { name = "ليزجية", codes = {} },
    lg = { name = "جاندا", codes = { "lug" } },
    li = { name = "ليمبورغية", codes = { "lim" } },
    lmo = { name = "لومباردية", codes = {} },
    ln = { name = "لينغالا", codes = { "lin" } },
    lo = { name = "لاوية", codes = { "lao" } },
    lou = { name = "كريولية لويزيانية", codes = {} },
    lrc = { name = "لرية شمالية", codes = {} },
    lt = { name = "ليتوانية", codes = { "lit" } },
    lu = { name = "تشيلوبا", codes = { "lub" } },
    lv = { name = "لاتفية", codes = { "lav" } },
    mfe = { name = "كريولية موريشية", codes = {} },
    mg = { name = "ملغاشية", codes = { "mlg" } },
    mh = { name = "مارشالية", codes = { "mah" } },
    mi = { name = "ماورية", codes = { "mri", "mao", "mri" } },
    mic = { name = "ميكماكيونية", codes = {} },
    ["mis-x-ripuar"] = { name = "ريبوارية", codes = {} },
    mk = { name = "مقدونية", codes = { "mkd", "mac", "mkd" } },
    ml = { name = "ماليالامية", codes = { "mal" } },
    mn = { name = "منغولية", codes = { "mon" } },
    mni = { name = "مانيبورية", codes = {} },
    mo = { name = "مولدوفية", codes = { "mol" } },
    mr = { name = "مراثية", codes = { "mar" } },
    ms = { name = "ملايوية", codes = { "msa", "may", "msa" } },
    mt = { name = "مالطية", codes = { "mlt" } },
    mul = { name = "لغات متعددة", codes = {} },
    mwr = { name = "ماروارية", codes = {} },
    my = { name = "بورمية", codes = { "mya", "bur", "mya" } },
    myv = { name = "أرزية", codes = {} },
    mzn = { name = "طبرية", codes = {} },
    na = { name = "ناورونية", codes = { "nau" } },
    nan = { name = "مين-نان صينية", codes = {} },
    ["nan-tw"] = { name = "هوكينة تايوانية", codes = {} },
    nap = { name = "نابولية", codes = {} },
    nb = { name = "نرويجية بوكمول", codes = { "nob", "nb-no" } },
    nd = { name = "نديبيل شمالية", codes = { "nde" } },
    nds = { name = "ألمانية دنيا", codes = {} },
    ne = { name = "نيبالية", codes = { "nep" } },
    new = { name = "نوارية", codes = {} },
    ng = { name = "ندونجا", codes = { "ndo" } },
    nl = { name = "هولندية", codes = { "nld", "dut", "nld" } },
    nl_BE = { name = "فلمنكية", codes = {} },
    nn = { name = "نرويجية نينوشك", codes = { "nno" } },
    no = { name = "نرويجية", codes = { "nor" } },
    non = { name = "إسكندنافية قديمة", codes = {} },
    nr = { name = "نديبلي جنوبية", codes = { "nbl" } },
    nrf = { name = "نورمندية", codes = { "roa", "nrf" } },
    nso = { name = "سوتو شمالية", codes = {} },
    nv = { name = "نافاجو", codes = { "nav" } },
    nwc = { name = "نوارية تقليدية", codes = {} },
    ny = { name = "شيشيوا", codes = { "nya" } },
    oc = { name = "أكستانية", codes = { "oci" } },
    oj = { name = "أوجيبوا", codes = { "oji" } },
    om = { name = "أورومية", codes = { "orm" } },
    ["or"] = { name = "أوريا", codes = { "ori" } },
    os = { name = "أوسيتية", codes = { "oss" } },
    ota = { name = "تركية عثمانية", codes = {} },
    pa = { name = "بنجابية", codes = { "pan" } },
    pal = { name = "بهلوية", codes = {} },
    pcm = { name = "بدجنية نيجيرية", codes = {} },
    peo = { name = "فارسية قديمة", codes = {} },
    pga = { name = "عربية كريولية سودانية", codes = {} },
    phn = { name = "فينيقية", codes = {} },
    pi = { name = "بالية", codes = { "pli" } },
    pl = { name = "بولندية", codes = { "pol", "pols" } },
    pms = { name = "بيدمونتية", codes = {} },
    pnt = { name = "جسرية", codes = {} },
    prg = { name = "بروسياوية", codes = {} },
    pro = { name = "بروفانسية قديمة", codes = {} },
    ps = { name = "بشتوية", codes = { "pus" } },
    pt = { name = "برتغالية", codes = { "por", "pt_PT", "pt-pt" } },
    ["pt-br"] = { name = "برتغالية برازيلية", codes = { "pt-br", "pt_BR" } },
    qu = { name = "كتشوا", codes = { "que" } },
    raj = { name = "راجاسثانية", codes = {} },
    rif = { name = "ريفية", codes = {} },
    rm = { name = "رومانشية", codes = { "roh" } },
    rn = { name = "كيروندية", codes = { "run" } },
    ro = { name = "رومانية", codes = { "ron", "rum", "ron" } },
    rom = { name = "غجرية", codes = {} },
    ro_MD = { name = "مولدوفية", codes = {} },
    ru = { name = "روسية", codes = { "rus" } },
    rw = { name = "روندية", codes = { "kin" } },
    sa = { name = "سنسكريتية", codes = { "san" } },
    sah = { name = "ساخية", codes = {} },
    sam = { name = "آرامية سامرية", codes = {} },
    sc = { name = "سردينية", codes = { "srd" } },
    scn = { name = "صقلية", codes = {} },
    sco = { name = "إسكتلندية", codes = {} },
    sd = { name = "سندية", codes = { "snd" } },
    sdh = { name = "كردية جنوبية", codes = {} },
    se = { name = "سامي شمالية", codes = { "sme" } },
    sg = { name = "سانغوية", codes = { "sag" } },
    sga = { name = "أيرلندية قديمة", codes = {} },
    sh = { name = "صربوكرواتية", codes = { "hbs" } },
    shi = { name = "شلحية", codes = {} },
    shu = { name = "عربية تشادية", codes = {} },
    si = { name = "سنهالية", codes = { "sin" } },
    sk = { name = "سلوفاكية", codes = { "slk", "slo", "slk" } },
    sl = { name = "سلوفينية", codes = { "slv" } },
    sm = { name = "ساموية", codes = { "smo" } },
    sma = { name = "سامية جنوبية", codes = {} },
    sn = { name = "شونا", codes = { "sna" } },
    so = { name = "صومالية", codes = { "som" } },
    sq = { name = "ألبانية", codes = { "sqi", "alb", "sqi" } },
    sr = { name = "صربية", codes = { "srp", "scc" } },
    ["sr-ec"] = { name = "صربية سيريلية", codes = { "sr-ec", "sr-ec" } },
    ["sr-el"] = { name = "صربية لاتينية", codes = { "sr-el", "sr-el" } },
    ss = { name = "سوازي", codes = { "ssw" } },
    ssh = { name = "عربية شحية", codes = {} },
    st = { name = "سوتية", codes = { "sot" } },
    su = { name = "سوندية", codes = { "sun" } },
    sux = { name = "سومارية", codes = {} },
    sv = { name = "سويدية", codes = { "swe" } },
    sw = { name = "سواحلية", codes = { "swa" } },
    swb = { name = "قمرية", codes = {} },
    syc = { name = "سريانية", codes = { "syr" } },
    ta = { name = "تاميلية", codes = { "tam" } },
    te = { name = "تيلوغوية", codes = { "tel" } },
    tg = { name = "طاجيكية", codes = { "tgk" } },
    th = { name = "تايلندية", codes = { "tha" } },
    ti = { name = "تغرينية", codes = { "tir" } },
    tig = { name = "تيغرية", codes = {} },
    tk = { name = "تركمانية", codes = { "tuk" } },
    tl = { name = "تاغالوغية", codes = { "tgl" } },
    tli = { name = "تلينغيتية", codes = {} },
    tn = { name = "تسوانية", codes = { "tsn" } },
    to = { name = "تونغية", codes = { "ton" } },
    tr = { name = "تركية", codes = { "tur" } },
    ts = { name = "تسونجا", codes = { "tso" } },
    tulu = { name = "تولو", codes = { "Tulu", "tcy" } },
    tw = { name = "توي", codes = { "twi" } },
    ty = { name = "تاهيتية", codes = { "tah" } },
    tyv = { name = "توفية", codes = {} },
    tzm = { name = "أطلسية", codes = {} },
    ug = { name = "أويغورية", codes = { "uig" } },
    uk = { name = "أوكرانية", codes = { "ukr" } },
    ur = { name = "أردوية", codes = { "urd" } },
    uz = { name = "أوزبكية", codes = { "uzb" } },
    ve = { name = "فيندية", codes = { "ven" } },
    vi = { name = "فيتنامية", codes = { "vie" } },
    vo = { name = "فولابوكية", codes = { "vol" } },
    wa = { name = "والونية", codes = { "wln" } },
    wlm = { name = "ويلزية وسطى", codes = {} },
    wo = { name = "ولوفية", codes = { "wol" } },
    wuu = { name = "وو صينية", codes = {} },
    xh = { name = "خوسية", codes = { "xho", "كوسية" } },
    xmf = { name = "منغريلية", codes = {} },
    xpu = { name = "بونيقية", codes = {} },
    yi = { name = "يديشية", codes = { "yid" } },
    yo = { name = "يوربا", codes = { "yor" } },
    yue = { name = "كانتونية", codes = { "yue", "zh-yue-Hani" } },
    za = { name = "زهيونج", codes = { "zha" } },
    zgh = { name = "أمازيغية معيارية مغربية", codes = {} },
    zh = { name = "صينية", codes = { "zho", "chi", "zh-Hani", "zh-cn" } },
    zu = { name = "زولوية", codes = { "zul" } },
    zun = { name = "زونية", codes = {} },
    ["zh-classical"] = { name = "كلاسيكية صينية", codes = {} },
    ["zh-hans"] = { name = "صينية مبسطة", codes = { "zh-s", "zh-tw", "zh-Hans", "zh_Hans" } },
    ["zh-hant"] = { name = "صينية تقليدية", codes = { "zh-t", "zh-Hant", "zh_Hant" } },
    ["zh-yue"] = { name = "كانتونية", codes = {} },
}

data.lang_name = {}
data.lang_name_with_al = {}
data.lang_codes = {}

for code, v in pairs(data.lang_table) do
    local name, al_name, codes = v.name, v.al_name, v.codes

    -- ربط اسم اللغة برمز اللغة في جدول `lang_name`
    data.lang_name[code] = name
    data.lang_name[code:lower()] = name

    -- ربط اسم اللغة برمز اللغة في جدول `lang_codes`
    data.lang_codes[name] = code

    -- إذا كان هناك اسم بديل للغة، فربطه برمز اللغة في جدول `lang_name_with_al`
    if al_name then
        data.lang_name_with_al[code] = al_name
        data.lang_name_with_al[code:lower()] = al_name
        data.lang_codes[al_name] = code
    end

    -- إذا كانت هناك أسماء متعددة للغة، فربطها جميعًا برمز اللغة في جدول `lang_codes`
    if v.names then
        for _, alias in ipairs(v.names) do
            data.lang_codes[alias] = code
        end
    end

    for _, lang_code in ipairs(codes) do
        -- ربط اسم اللغة برمز اللغة في جدول `lang_name`
        data.lang_name[lang_code:lower()] = name

        -- إذا كان هناك اسم بديل للغة، فربطه برمز اللغة في جدول `lang_name_with_al`
        if al_name then
            data.lang_name_with_al[lang_code] = al_name
            data.lang_name_with_al[lang_code:lower()] = al_name
        end
    end
end

return data
